export default {
    NEW_USER_ERRORED: 'NEW_USER_ERRORED',
    NEW_USER_SAVED: 'NEW_USER_SAVED',
    NEW_USER_SAVING: 'NEW_USER_SAVING',

    CONSENT_ACCEPT: 'CONSENT_ACCEPT',
    CONSENT_DECLINE: 'CONSENT_DECLINE',

    START_ELIGIBILITY_SURVEY_ERRORED: 'START_ELIGIBILITY_SURVEY_ERRORED',
    START_ELIGIBILITY_SURVEY_SAVED: 'START_ELIGIBILITY_SURVEY_SAVED',
    START_ELIGIBILITY_SURVEY_SAVING: 'START_ELIGIBILITY_SURVEY_SAVING',

    END_ELIGIBILITY_SURVEY_ERRORED: 'END_ELIGIBILITY_SURVEY_ERRORED',
    END_ELIGIBILITY_SURVEY_SAVED: 'END_ELIGIBILITY_SURVEY_SAVED',
    END_ELIGIBILITY_SURVEY_SAVING: 'END_ELIGIBILITY_SURVEY_SAVING',

    START_SURVEY_ERRORED: 'START_SURVEY_ERRORED',
    START_SURVEY_SAVED: 'START_SURVEY_SAVED',
    START_SURVEY_SAVING: 'START_SURVEY_SAVING'
};
