export default {
    CONSENT_ACCEPT: 'CONSENT_ACCEPT',
    CONSENT_DECLINE: 'CONSENT_DECLINE',

    NEW_USER_SAVED: 'NEW_USER_SAVED',

    REQUEST_ERRORED: 'REQUEST_ERRORED',
    REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',

    START_DEMOGRAPHICS_SURVEY_SAVED: 'START_DEMOGRAPHICS_SURVEY_SAVED',
    END_DEMOGRAPHICS_SURVEY_SAVED: 'END_DEMOGRAPHICS_SURVEY_SAVED',

    START_ELIGIBILITY_SURVEY_SAVED: 'START_ELIGIBILITY_SURVEY_SAVED',
    END_ELIGIBILITY_SURVEY_SAVED: 'END_ELIGIBILITY_SURVEY_SAVED',

    GET_USER_COMPLETE: 'GET_USER_COMPLETE',
    IS_LOADING_SURVEY: 'IS_LOADING_SURVEY',
    START_SURVEY_SAVED: 'START_SURVEY_SAVED',
    RATE_PICTURE_SAVED: 'RATE_PICTURE_SAVED',
    END_SURVEY_SAVED: 'END_SURVEY_SAVED',

    FETCHING_DESIRABILITY_REPORT_DATA_COMPLETE: 'FETCHING_DESIRABILITY_REPORT_DATA_COMPLETE',
    FETCHING_ELIGIBILITY_COMPLETION_REPORT_DATA_COMPLETE: 'FETCHING_ELIGIBILITY_COMPLETION_REPORT_DATA_COMPLETE',
    FETCHING_INVITATION_REPORT_DATA_COMPLETE: 'FETCHING_INVITATION_REPORT_DATA_COMPLETE',
    FETCHING_PROGRESS_REPORT_DATA_COMPLETE: 'FETCHING_PROGRESS_REPORT_DATA_COMPLETE',
    FETCHING_RECOGNIZABILITY_REPORT_DATA_COMPLETE: 'FETCHING_RECOGNIZABILITY_REPORT_DATA_COMPLETE',
    FETCHING_SURVEY_COMPLETION_REPORT_DATA_COMPLETE: 'FETCHING_SURVEY_COMPLETION_REPORT_DATA_COMPLETE'
};
