export default {
    CONSENT_ACCEPT: 'CONSENT_ACCEPT',
    CONSENT_DECLINE: 'CONSENT_DECLINE',

    NEW_USER_SAVED: 'NEW_USER_SAVED',

    REQUEST_ERRORED: 'REQUEST_ERRORED',
    REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',

    START_ELIGIBILITY_SURVEY_SAVED: 'START_ELIGIBILITY_SURVEY_SAVED',
    END_ELIGIBILITY_SURVEY_SAVED: 'END_ELIGIBILITY_SURVEY_SAVED',

    START_SURVEY_SAVED: 'START_SURVEY_SAVED',
    GET_USER_COMPLETE: 'GET_USER_COMPLETE',
    END_SURVEY_SAVED: 'END_SURVEY_SAVED',

    FETCHING_REPORT_DATA_ERRORED: 'FETCHING_REPORT_DATA_ERRORED',
    FETCHING_REPORT_DATA_IN_PROGRESS: 'FETCHING_REPORT_DATA_IN_PROGRESS',

    FETCHING_COMPLETION_REPORT_DATA_COMPLETE: 'FETCHING_COMPLETION_REPORT_DATA_COMPLETE',
    FETCHING_ELIGIBILITY_REPORT_DATA_COMPLETE: 'FETCHING_ELIGIBILITY_REPORT_DATA_COMPLETE'
};
