// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinStim.Models;

namespace SinStim.Migrations
{
    [DbContext(typeof(SinStimContext))]
    [Migration("20190912034631_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SinStim.Models.Demographics", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Education");

                    b.Property<DateTimeOffset?>("EndTime");

                    b.Property<string>("Gender");

                    b.Property<string>("MartialStatus");

                    b.Property<string>("Race_Arab");

                    b.Property<string>("Race_Asian_PacificIslander");

                    b.Property<string>("Race_Black_AfricanAmerican");

                    b.Property<string>("Race_Hispanic_Latino");

                    b.Property<string>("Race_Indigenous_Aboriginal");

                    b.Property<string>("Race_NoReponse");

                    b.Property<string>("Race_Other");

                    b.Property<string>("Race_White_Caucasian");

                    b.Property<DateTimeOffset?>("StartTime");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Demographics");
                });

            modelBuilder.Entity("SinStim.Models.Eligibility", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Alcohol");

                    b.Property<bool?>("Chocolate");

                    b.Property<bool?>("Cocaine");

                    b.Property<bool?>("Cookies");

                    b.Property<bool?>("Donuts");

                    b.Property<bool?>("Fries");

                    b.Property<bool?>("Heroin");

                    b.Property<bool?>("IceCream");

                    b.Property<bool?>("Marijuana");

                    b.Property<bool?>("Methamphetamine");

                    b.Property<bool?>("Pasta");

                    b.Property<bool?>("Pills");

                    b.Property<bool?>("Pizza");

                    b.Property<bool?>("Tobacco");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Eligibilities");
                });

            modelBuilder.Entity("SinStim.Models.Picture", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("FileName");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("SinStim.Models.Rating", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Desirability");

                    b.Property<string>("PictureId");

                    b.Property<int?>("Recognizability");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SinStim.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedCategory");

                    b.Property<string>("EligibilityCompletionCode");

                    b.Property<DateTimeOffset?>("EligibilityEndTime");

                    b.Property<DateTimeOffset?>("EligibilityStartTime");

                    b.Property<bool>("IsRejected");

                    b.Property<string>("SurveyCompletionCode");

                    b.Property<DateTimeOffset?>("SurveyEndTime");

                    b.Property<DateTimeOffset?>("SurveyStartTime");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SinStim.Models.Demographics", b =>
                {
                    b.HasOne("SinStim.Models.User", "User")
                        .WithOne("Demographics")
                        .HasForeignKey("SinStim.Models.Demographics", "UserId");
                });

            modelBuilder.Entity("SinStim.Models.Eligibility", b =>
                {
                    b.HasOne("SinStim.Models.User", "User")
                        .WithOne("Eligibility")
                        .HasForeignKey("SinStim.Models.Eligibility", "UserId");
                });

            modelBuilder.Entity("SinStim.Models.Rating", b =>
                {
                    b.HasOne("SinStim.Models.Picture", "Picture")
                        .WithMany("Ratings")
                        .HasForeignKey("PictureId");

                    b.HasOne("SinStim.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
