USE [master]
GO
/****** Object:  Database [SinStim]    Script Date: 5/15/2018 11:16:33 PM ******/
CREATE DATABASE [SinStim]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'SinStim', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SinStim.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'SinStim_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SinStim_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SinStim] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SinStim].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SinStim] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SinStim] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SinStim] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SinStim] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SinStim] SET ARITHABORT OFF
GO
ALTER DATABASE [SinStim] SET AUTO_CLOSE ON
GO
ALTER DATABASE [SinStim] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SinStim] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SinStim] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SinStim] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SinStim] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SinStim] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SinStim] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SinStim] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SinStim] SET  ENABLE_BROKER
GO
ALTER DATABASE [SinStim] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SinStim] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SinStim] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SinStim] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SinStim] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SinStim] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SinStim] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SinStim] SET RECOVERY SIMPLE
GO
ALTER DATABASE [SinStim] SET  MULTI_USER
GO
ALTER DATABASE [SinStim] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SinStim] SET DB_CHAINING OFF
GO
ALTER DATABASE [SinStim] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [SinStim] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [SinStim] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [SinStim] SET QUERY_STORE = OFF
GO
USE [SinStim]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [SinStim]
GO
/****** Object:  Table [dbo].[ELIGIBILITIES]    Script Date: 5/15/2018 11:16:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELIGIBILITIES](
	[ID] [uniqueidentifier] NOT NULL,
	[USER_ID] [nvarchar](50) NOT NULL,
	[NEUTRAL] [bit] NULL,
	[ALCOHOL] [bit] NULL,
	[TOBACCO] [bit] NULL,
	[COCAINE] [bit] NULL,
	[HEROIN] [bit] NULL,
	[MARIJUANA] [bit] NULL,
	[METHAMPHETAMINE] [bit] NULL,
	[PILLS] [bit] NULL,
	[CHOCOLATE] [bit] NULL,
	[COOKIES] [bit] NULL,
	[DONUTS] [bit] NULL,
	[FRIES] [bit] NULL,
	[ICE_CREAM] [bit] NULL,
	[PASTA] [bit] NULL,
	[PIZZA] [bit] NULL,
 CONSTRAINT [PK_ELIGIBILITY] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PICTURES]    Script Date: 5/15/2018 11:16:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PICTURES](
	[ID] [uniqueidentifier] NOT NULL,
	[PATH] [nvarchar](max) NOT NULL,
	[FILE_NAME] [nvarchar](50) NOT NULL,
	[CATEGORY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PICTURE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RATINGS]    Script Date: 5/15/2018 11:16:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RATINGS](
	[ID] [uniqueidentifier] NOT NULL,
	[USER_ID] [nvarchar](50) NOT NULL,
	[PICTURE_ID] [uniqueidentifier] NOT NULL,
	[RECOGNIZABILITY] [int] NULL,
	[DESIRABILITY] [int] NULL,
 CONSTRAINT [PK_RATING] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 5/15/2018 11:16:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[ID] [nvarchar](50) NOT NULL,
	[IS_REJECTED] [bit] NOT NULL,
	[SURVEY_START_TIME] [datetimeoffset](7) NULL,
	[SURVEY_END_TIME] [datetimeoffset](7) NULL,
	[TASK_START_TIME] [datetimeoffset](7) NULL,
	[TASK_END_TIME] [datetimeoffset](7) NULL,
	[ASSIGNED_CATEGORY] [nvarchar](50) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USER_IS_ELIGIBLE_1]  DEFAULT ((0)) FOR [IS_REJECTED]
GO
ALTER TABLE [dbo].[ELIGIBILITIES]  WITH CHECK ADD  CONSTRAINT [FK_ELIGIBILITY_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[ELIGIBILITIES] CHECK CONSTRAINT [FK_ELIGIBILITY_USER]
GO
ALTER TABLE [dbo].[RATINGS]  WITH CHECK ADD  CONSTRAINT [FK_RATINGS_PICTURES] FOREIGN KEY([PICTURE_ID])
REFERENCES [dbo].[PICTURES] ([ID])
GO
ALTER TABLE [dbo].[RATINGS] CHECK CONSTRAINT [FK_RATINGS_PICTURES]
GO
ALTER TABLE [dbo].[RATINGS]  WITH CHECK ADD  CONSTRAINT [FK_RATINGS_USERS] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[RATINGS] CHECK CONSTRAINT [FK_RATINGS_USERS]
GO
USE [master]
GO
ALTER DATABASE [SinStim] SET  READ_WRITE
GO
